@startuml

class Guest {
   id : Int
   firstName : String
   lastName : String
   telefonNumber : String
}

class Product {
   Guest: Guest
   Cook : Cook
   id : Int
   name : String
   price : Double
}

class Cook {
   id : Int
   firstName : String
   lastName : String
   entryDate: LocalDate
   salary: Double
}

Product "*" -left-> "1"  Guest: has
Product "*" -right-> "1"  Cook: is made by


@enduml
